// pub mod login_handler;
// pub mod register_handler;
pub mod first_handler;
// pub mod artical_handler;
// pub mod detail_handler;
// pub mod comment_handler;
// pub mod tags_handler;
// pub mod favorite_handler;
// pub mod isfavorite_handler;
// pub mod addcomment_handler;
// pub mod save_draft_handler;
// pub mod drafts_handler;
// pub mod draft_handler;
// pub mod update_draft_handler;
// pub mod delete_draft_handler;
// pub mod publish_handler;
// pub mod categories_handler;
// pub mod articles_admin_handler;
// pub mod comment_admin_handler;
// pub mod tags_list_handler;
// pub mod get_register_handler;
// pub mod logout_handler;

pub mod user_handlers;
pub mod article_handlers;
pub mod draft_handlers;
pub mod admin_handlers;
