//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

pub use super::articles::Entity as Articles;
pub use super::comments::Entity as Comments;
pub use super::favorite::Entity as Favorite;
pub use super::markdowns::Entity as Markdowns;
pub use super::tags::Entity as Tags;
pub use super::tags_articles::Entity as TagsArticles;
pub use super::users::Entity as Users;
